name: noeng-wf-dmx-demo
base: core18
version: '0.1'
summary: Control a light with example DMX commands
description: |
  Example script to send some DMX commands for a sequence of color flashes
  to a light via USB RS-485 interface.

grade: devel
confinement: devmode

parts:
  hello:
    plugin: python
    python-version: python3
    source: .

apps:
  noeng-wf-dmx-demo:
    command: bin/hello
