name: noeng-wf-dmx-demo
base: core18
version: '0.1'
summary: Control a light with example DMX commands
description: |
  Example script to send some DMX commands for a sequence of color flashes
  to a light via USB RS-485 interface.

grade: devel
confinement: devmode

parts:
  python3-src:
    plugin: python
    python-version: python3
    source: python3-src
  cpp-src:
    plugin: cmake
    source: cpp-src
  rust-src:
    plugin: rust
    source: rust-src

apps:
  hello:
    command: bin/hello
  set-color:
    command: bin/set-color
  hello-cpp:
    command: hello-cpp
  hello-rust:
    command: hello-rust
