name: noeng-wf-dmx-demo
base: core18
version: '0.1'
summary: Control a light with example DMX commands
description: |
  Example script to send some DMX commands for a sequence of color flashes
  to a light via USB RS-485 interface.

grade: stable
confinement: strict

parts:
  python3-src:
    plugin: python
    python-version: python3
    source: python3-src
  cpp-src:
    plugin: cmake
    source: cpp-src

plugs:
  serial-port-usb:
    interface: serial-port

apps:
  hello:
    command: bin/hello
  set-color:
    command: bin/set-color
    plugs: [serial-port-usb]
  hello-cpp:
    command: hello-cpp
  color-sequence:
    command: color-sequence
    daemon: simple
    restart-condition: always
    plugs: [serial-port-usb]
